import localFont from "next/font/local";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import StoreProvider from "./components/StoreProvider";
import { ToastContainer } from "react-toastify";

const vazirmatn = localFont({
	src: "./Vazir.woff2",
	display: "swap",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<StoreProvider>
				<body className={vazirmatn.className}>
					<ToastContainer />
					{children}
				</body>
			</StoreProvider>
		</html>
	);
}
